on: [push]
name: Azure ARM deploy ENode
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZDEPLOY }}

      # Deploy ARM template
    - name: Run ARM ENODE
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZSUB }}
        resourceGroupName: ${{ secrets.AZRG }}
        template: ./node.json
        parameters: ./node-params.json
        
      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
